version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: robovers-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: robovers
      MYSQL_USER: robovers
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: robovers-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: